# -*- coding: utf-8 -*-
"""streamlit_app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P4VLS2Xweo6pd9v4n02_06eFdZvu1si-
"""

pip install streamlit

"""# Text Input"""

import streamlit as st

name = st.text_input(label='Nama lengkap', value='')
st.write('Nama: ', name)

